### PR TITLE
Unblock reconciliation during synthesis

### LINKED ISSUE #229: Store a third synthesis
Each composition has a max of two syntheses - current and previous. This allows Eno to compute three-way patches but only when the current synthesis has succeeded. So the reconciliation loop is broken during synthesis.

This is fine for most cases, but ideally reconciliation could continue regardless of synthesis state to handle cases where synthesis fails terminally.

### PR DESCRIPTION
**Pull request by jveski**
Resolves #229.

Since Eno only currently retains two syntheses, it isn't possible to (correctly) reconcile resources while synthesis is in-progress. So configuration might drift in cases where synthesis is slow.

It isn't a huge problem currently since synthesis is fast, but keeping a third synthesis ends up significantly simplifying the synthesis controller, which I'm working on property-based tests and refactoring for currently.

This change adds an "in flight" synthesis that is swapped into the existing "current" slot when synthesis is complete. I tried not to touch unrelated code - the diff mostly just swaps synthesis references, with a few exceptions (I'll leave PR comments to clarify).

## Backcompat

- Compositions with `CurrentSynthesis.Synthesized != nil` are unaffected - this is still the terminal state
- Compositions with `CurrentSynthesis == nil` are unaffected since the new code will be used for synthesis
- Compositions with `CurrentSynthesis != nil && CurrentSynthesis.Synthesized == nil` (a.k.a. in-flight synthesis) will converge eventually because the scheduling controller considers `(CurrentSynthesis.Synthesized == nil) == (CurrentSynthesis == nil)`

### CODE REVIEW

File: api/v1/composition.go [hunk 1]
```diff
@@ -52,6 +52,7 @@ type CompositionSpec struct {
 
 type CompositionStatus struct {
 	Simplified         *SimplifiedStatus `json:"simplified,omitempty"`
+	PendingSynthesis   *Synthesis        `json:"pendingSynthesis,omitempty"`
```
Comment (jveski) [inline api/v1/composition.go:55]: Does "pending" make sense here? Maybe "Active"? or "InFlight"?

File: internal/controllers/reconciliation/crud_test.go [hunk 2]
```diff
@@ -702,59 +702,6 @@ func TestDisableUpdates(t *testing.T) {
 	assert.Equal(t, "baz", obj.Data["foo"])
 }
 
-// TestOrphanedCompositionDeletion proves that compositions can be deleted when their synthesizer is missing.
-func TestOrphanedCompositionDeletion(t *testing.T) {
```
Comment (jveski) [inline internal/controllers/reconciliation/crud_test.go:706]: The logic that made this test pass would be... tricky to get working after this change. That said, I don't personally really care about the behavior at least until some other refactoring is done. Open to commenting out the test with a TODO if folks would prefer, but ultimately I don't think it's the right place to test this behavior anyway.

File: internal/controllers/scheduling/controller.go [hunk 3]
```diff
@@ -161,9 +161,10 @@ func (c *controller) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
 func (c *controller) getNextCooldownSlot(comps *apiv1.CompositionList) time.Time {
 	var next time.Time
 	for _, comp := range comps.Items {
-		syn := comp.Status.CurrentSynthesis
-		if syn != nil && syn.Deferred && syn.Initialized != nil && syn.Initialized.Time.After(next) {
-			next = syn.Initialized.Time
+		for _, syn := range []*apiv1.Synthesis{comp.Status.PendingSynthesis, comp.Status.CurrentSynthesis, comp.Status.PreviousSynthesis} {
```
Comment (jveski) [inline internal/controllers/scheduling/controller.go:164]: It was kind of a bug to not check PreviousSynthesis before 🤷‍♂️

File: internal/controllers/synthesis/lifecycle.go [hunk 4]
```diff
@@ -198,37 +199,16 @@ func (c *podLifecycleController) Reconcile(ctx context.Context, req ctrl.Request
 func (c *podLifecycleController) reconcileDeletedComposition(ctx context.Context, comp *apiv1.Composition) (ctrl.Result, error) {
 	logger := logr.FromContextOrDiscard(ctx)
 
-	// If the composition was being synthesized at the time of deletion we need to swap the previous
-	// state back to current. Otherwise we'll get stuck waiting for a synthesis that can't happen.
-	if shouldRevertStateSwap(comp) {
```
Comment (jveski) [inline internal/controllers/synthesis/lifecycle.go:203]: We don't need this any more!

File: api/v1/composition.go (hunk 1 above)
Comment (chihshenghuang) [reply api/v1/composition.go:55]: I like "InFlight" :grin:

Comment (jveski) [reply api/v1/composition.go]: Done!

File: internal/controllers/reconciliation/crud_test.go (hunk 2 above)
Comment (AYM1607) [reply internal/controllers/reconciliation/crud_test.go:706]: I'm okay with deleting this and opening up an issue that points to this PR if we care enough about the behavior to test it after the refactor.

File: api/v1/composition.go [hunk 5]
```diff
@@ -224,7 +225,7 @@ func (c *Composition) ShouldIgnoreSideEffects() bool {
 }
 
 func (c *Composition) Synthesizing() bool {
-	return c.Status.CurrentSynthesis != nil && c.Status.CurrentSynthesis.Synthesized == nil
+	return c.Status.InFlightSynthesis != nil
```
Comment (AYM1607) [inline api/v1/composition.go:228]: Clean 😼

File: docs/api.md [hunk 6]
```diff
@@ -92,6 +92,7 @@ _Appears in:_
 | Field | Description | Default | Validation |
 | --- | --- | --- | --- |
 | `simplified` _[SimplifiedStatus](#simplifiedstatus)_ |  |  |  |
+| `inFlightSynthesis` _[Synthesis](#synthesis)_ |  |  |  |
```
Comment (AYM1607) [inline docs/api.md:95]: Maybe we should start adding more comments to the api structs so we can use this auto-gen files as proper docs

File: internal/controllers/synthesis/lifecycle.go [hunk 7]
```diff
@@ -68,8 +69,8 @@ func (c *podLifecycleController) Reconcile(ctx context.Context, req ctrl.Request
 
 	logger = logger.WithValues("compositionName", comp.Name,
 		"compositionNamespace", comp.Namespace,
-		"compositionGeneration", comp.Generation,
-		"synthesisID", comp.Status.GetCurrentSynthesisUUID())
```
Comment (AYM1607) [inline internal/controllers/synthesis/lifecycle.go:72]: Replace with get latest uuid?

File: api/v1/config/crd/eno.azure.io_synthesizers.yaml [hunk 8]
```diff
@@ -350,7 +350,7 @@ spec:
                                         pod labels will be ignored. The default value is empty.
                                         The same key is forbidden to exist in both matchLabelKeys and labelSelector.
                                         Also, matchLabelKeys cannot be set when labelSelector isn't set.
-                                        This is an alpha field and requires enabling MatchLabelKeysInPodAffinity feature gate.
+                                        This is a beta field and requires enabling MatchLabelKeysInPodAffinity feature gate (enabled by default).
```
[the remark this answers is not in the document]
Comment (jveski) [reply api/v1/config/crd/eno.azure.io_synthesizers.yaml:353]: I must have updated controller-gen on my devbox recently 😆

File: internal/controllers/synthesis/lifecycle.go (hunk 7 above)
Comment (AYM1607) [reply internal/controllers/synthesis/lifecycle.go:72]: I see, it's not relevant until we know that we're acting upon the in flight uuid.

File: docs/api.md (hunk 6 above)
Comment (jveski) [reply docs/api.md:95]: Agreed - we're pretty close on a few structs but most of them are still lacking

File: internal/controllers/synthesis/lifecycle.go [hunk 9]
```diff
@@ -136,15 +136,17 @@ func (c *podLifecycleController) Reconcile(ctx context.Context, req ctrl.Request
...
 	}
+	logger = logger.WithValues("synthesisID", comp.Status.InFlightSynthesis.UUID)
+	ctx = logr.NewContext(ctx, logger)
 
 	// Back off to avoid constantly re-synthesizing impossible compositions (unlikely but possible)
 	if shouldBackOffPodCreation(comp) {
 		const base = time.Millisecond * 250
-		wait := base * time.Duration(comp.Status.CurrentSynthesis.Attempts)
-		nextAttempt := comp.Status.CurrentSynthesis.PodCreation.Time.Add(wait)
+		wait := base * time.Duration(comp.Status.InFlightSynthesis.Attempts)
```
Comment (AYM1607) [inline internal/controllers/synthesis/lifecycle.go:148]: I think we had this conversation already, but could you remind me why we're not doing exponential here?

File: internal/controllers/scheduling/controller.go [hunk 10]
```diff
@@ -161,9 +161,10 @@ func (c *controller) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
 func (c *controller) getNextCooldownSlot(comps *apiv1.CompositionList) time.Time {
 	var next time.Time
 	for _, comp := range comps.Items {
-		syn := comp.Status.CurrentSynthesis
-		if syn != nil && syn.Deferred && syn.Initialized != nil && syn.Initialized.Time.After(next) {
-			next = syn.Initialized.Time
+		for _, syn := range []*apiv1.Synthesis{comp.Status.InFlightSynthesis, comp.Status.CurrentSynthesis, comp.Status.PreviousSynthesis} {
```
[the remark this answers is not in the document]
Comment (jveski) [reply internal/controllers/scheduling/controller.go:164]: IMO it's _kind of_ a bug to not check prev. But realistically synthesis is slow enough relative to the cooldown period that it wouldn't ever matter.

File: internal/controllers/synthesis/lifecycle.go (hunk 9 above)
Comment (jveski) [reply internal/controllers/synthesis/lifecycle.go:148]: No reason that I'm aware of lol

I have a half working PR that integrates the scheduling controller into the retry loop so retries will be prioritized correctly. That one will also switch to exponential backoff.

File: internal/controllers/synthesis/slicecleanup.go [hunk 11]
```diff
@@ -147,16 +147,22 @@ func (c *cleanupDecision) String() string {
 }
 
 func shouldDeleteSlice(comp *apiv1.Composition, slice *apiv1.ResourceSlice) bool {
-	if comp.Status.CurrentSynthesis == nil || slice.Spec.CompositionGeneration > comp.Status.CurrentSynthesis.ObservedCompositionGeneration {
+	var synthesizedGeneration int64
+	if comp.Status.InFlightSynthesis != nil {
```
[the remark this answers is not in the document]
Comment (jveski) [reply internal/controllers/synthesis/slicecleanup.go:151]: `InFlightSynthesis.Synthesized == true` is not currently possible since in-flight is always swapped to current synthesis by the executor. We can probably remove the property actually, just need to clean up the logs that depend on it

File: internal/controllers/synthesis/slicecleanup.go [hunk 12]
```diff
@@ -147,16 +147,22 @@ func (c *cleanupDecision) String() string {
...
-		isReferencedByComp = synthesisReferencesSlice(comp.Status.CurrentSynthesis, slice) || synthesisReferencesSlice(comp.Status.PreviousSynthesis, slice)
-		isSynthesized      = comp.Status.CurrentSynthesis.Synthesized != nil
+		hasBeenRetried     = slice.Spec.Attempt != 0 && comp.Status.InFlightSynthesis != nil && comp.Status.InFlightSynthesis.Attempts > slice.Spec.Attempt && slice.Spec.SynthesisUUID == comp.Status.InFlightSynthesis.UUID
+		isReferencedByComp = synthesisReferencesSlice(comp.Status.InFlightSynthesis, slice) || synthesisReferencesSlice(comp.Status.CurrentSynthesis, slice) || synthesisReferencesSlice(comp.Status.PreviousSynthesis, slice)
+		isSynthesized      = comp.Status.CurrentSynthesis != nil
 		compIsDeleted      = comp.DeletionTimestamp != nil
-		fromOldComposition = slice.Spec.CompositionGeneration < comp.Status.CurrentSynthesis.ObservedCompositionGeneration
+		fromOldComposition = comp.Status.CurrentSynthesis == nil || slice.Spec.CompositionGeneration < comp.Status.CurrentSynthesis.ObservedCompositionGeneration
```
[the remark this answers is not in the document]
Comment (jveski) [reply internal/controllers/synthesis/slicecleanup.go:165]: It means that the resource slice was derived from a composition generation that is < the current

File: internal/controllers/selfhealing/slice_test.go [hunk 13]
```diff
@@ -480,14 +480,14 @@ func TestNotEligibleForResynthesis(t *testing.T) {
 		{
 			name: "CurrentSynthesis Synthesized is nil",
```
[the remark this answers is not in the document]
Comment (AYM1607) [reply internal/controllers/selfhealing/slice_test.go:481]: Sure thing!

File: internal/controllers/synthesis/slicecleanup.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (jveski) [reply internal/controllers/synthesis/slicecleanup.go:165]: Hmm this might deserve more scrutiny actually

[the remark this answers is not in the document]
Comment (jveski) [reply internal/controllers/synthesis/slicecleanup.go:165]: Pushed some tests to help reason about this. I _think_ this effectively preserves the current logic, although I'm pretty sure the current logic doesn't make any sense

**Review by AYM1607 — APPROVED** [review]
